### ISSUE TITLE
np.nan

### ISSUE THREAD

**Issue by mtinti** [ShawnLYU/Quantile_Normalize#1]
Dear ShawnLYU,

nice piece of code! what you think about preserving np.nan values in the dataframe?
cheers

Michele

**Comment by coderfreestyle** [comment]
Thanks for your question :+1: 
First of all, this function was implemented without considering np.nan since we replaced any NaN with a certain value before normalization.
Secondly I think that sorting algorithms would rank np.nan as the largest one. Hope that could provide some clue about your question.
